version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: healthcare_rag_qdrant
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always
    environment:
      - QDRANT__LOG_LEVEL=INFO

  redis:
    image: redis:7-alpine
    container_name: healthcare_rag_redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
    restart: always
    command: redis-server --appendonly yes

  # Optional: Redis Commander for monitoring Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: healthcare_rag_redis_commander
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: always

volumes:
  qdrant_storage:
  redis_data:
